---
name: "RefreshSparse"
guid: "12b44f20-6cfb-4be5-9950-3d0fbe74fa35"
version: "4.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Refresh episodes based on (missing) metadata"
description: >
  Find episode that are recent and/or are missing certain
  metadata fields and refresh metadata on those episodes.
category: "General"
owner: "SenorSmartyPants"
artifacts:
- "Jellyfin.Plugin.RefreshSparse.dll"
changelog: >
  10.9.0 support
